# Generated by Django 5.0.4 on 2024-05-07 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfpps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='mod',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='cartao',
            field=models.ForeignKey(blank=True, help_text='Somente preencher se for usado crédito.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sfpps.cartao'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.ForeignKey(help_text='Classificar o tipo de gasto', on_delete=django.db.models.deletion.CASCADE, to='sfpps.categoria'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='pagamento',
            field=models.ForeignKey(help_text='Qual centro de pagamento está associado', on_delete=django.db.models.deletion.CASCADE, to='sfpps.pagamento'),
        ),
        migrations.DeleteModel(
            name='Modalidade',
        ),
    ]
